# -*- coding: utf-8 -*-
"""AImarket_Question1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtRbnnBXMLw6nAVsf67D5tzmrjhF1l1i
"""

import pandas as pd
import numpy as np

#load data
df = pd.read_csv('ai_job_dataset.csv')

print(f"Loaded Dataset: {df.shape[0]} rows, {df.shape[1]} columns")

df

# Explode skills column / data cleaning
df['skills_list'] = df['required_skills'].str.split(',')
df_skills = df.explode('skills_list')
df_skills['skills_list'] = df_skills['skills_list'].str.strip()

# Baseline salary
baseline = df['salary_usd'].median()

# Premium per skill
skill_premium = df_skills.groupby('skills_list')['salary_usd'].median()
skill_premium_pct = ((skill_premium - baseline) / baseline * 100).sort_values(ascending=False)
print(skill_premium_pct.head(15))

df_skills

skill_premium_pct

skill_premium_pct.to_csv('ai_jobs_skills_premium.csv', index=False)

skill_premium

df_premium_final = skill_premium_pct.reset_index()

df_premium_final.columns = ['skill', 'premium_pct']

df_premium_final.to_csv('ai_jobs_skills_premium.csv', index=False)