# -*- coding: utf-8 -*-
"""AImarket_Question2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNZ8BVQ3HlbcQTOBimLX0CIVcQ7FP4g3
"""

import pandas as pd
import numpy as np

#load data
df = pd.read_csv('ai_job_dataset.csv')
df

df['posting_date'] = pd.to_datetime(df['posting_date'])
df

df['quarter'] = df['posting_date'].dt.to_period('Q')
df

trend = df.groupby(['quarter', 'job_title']).agg(
    postings=('job_title', 'count'),
    avg_salary=('salary_usd', 'median')
).reset_index()
trend

q4 = trend[trend['quarter'] == '2024Q4']
q1 = trend[trend['quarter'] == '2025Q1']
merged = q4.merge(q1, on='job_title', suffixes=('_q4', '_q1'))
merged['posting_growth_pct'] = (merged['postings_q1'] - merged['postings_q4']) / merged['postings_q4'] * 100
merged['salary_growth_pct'] = (merged['avg_salary_q1'] - merged['avg_salary_q4']) / merged['avg_salary_q4'] * 100
print(merged.sort_values('posting_growth_pct', ascending=False))
merged

merged.to_csv('ai_market_growth_to2025.csv', index=False)

# Create trend by month
# use year-month
df['year_month'] = df['posting_date'].dt.strftime('%Y-%m')

trend_month = df.groupby(['year_month', 'job_title']).agg(
    postings=('job_title', 'count'),
    avg_salary=('salary_usd', 'median')
).reset_index()


trend_month = trend_month.sort_values('year_month')
trend_month.to_csv('ai_trends_monthly.csv', index=False)