# -*- coding: utf-8 -*-
"""AImarket_Question3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NxPN6HKjQOva6jbOmY9i6TsyBmlYEYW
"""

import pandas as pd
import numpy as np

#load data
df = pd.read_csv('ai_job_dataset.csv')

print(df.columns.tolist())
print(df.dtypes)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# posting_date as a string (object),
df['posting_date'] = pd.to_datetime(df['posting_date'])

df['quarter'] = df['posting_date'].dt.to_period('Q')

df['month'] = df['posting_date'].dt.to_period('M')

print("✅ Listo:", df.shape)
print(df['quarter'].value_counts().sort_index())

# ── BQ2: Salary + Benefits por company_size ──────────────────────────────────

bq2 = df.groupby('company_size').agg(
    avg_salary    = ('salary_usd',    'mean'),
    median_salary = ('salary_usd',    'median'),
    avg_benefits  = ('benefits_score','mean'),
    job_count     = ('job_id',        'count')
).reset_index()

bq2['total_comp_index'] = bq2['avg_salary'] + (bq2['avg_benefits'] * 1000)

bq2 = bq2.sort_values('total_comp_index', ascending=False)

print(bq2.round(2))

df

bq2.to_csv('metric_salary_ai.csv', index=False)

bq2